version: "3"

services:
  jni_tf_dev_container:
    container_name: "jni_tf_dev_container"
    image: jni_tf_dev_container
    user: "jni"
    restart: unless-stopped
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - .:/workspace:cached
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu] 
